apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
     - "--accesslog"
     - "--metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000"
     - "--metrics.prometheus.addEntryPointsLabels=true"
     - "--metrics.prometheus.addServicesLabels=true"
     - "--tracing.jaeger=true"
     - "--tracing.serviceName=traefik"
     - "--tracing.jaeger.collector.endpoint=http://my-otel-demo-otelcol.default.svc.cluster.local:14268/api/traces?format=jaeger.thrift"
