default:
  # list of environment variables applied to all components
  env:
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: "metadata.labels['app.kubernetes.io/component']"
    - name: OTEL_COLLECTOR_NAME
      value: '{{ include "otel-demo.name" . }}-otelcol'
    - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
      value: cumulative
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo
    - name: OTEL_METRICS_EXPORTER
      value: 'otlp'
    - name: OTEL_LOGS_EXPORTER
      value: 'otlp'

components:
  frontend:
    resources:
      limits:
        memory: 500Mi

opentelemetry-collector:
  config:
    exporters:
      ## Create an exporter to Jaeger using the standard `otlp` export format
      otlp/elastic:
        endpoint: <elastic-cloud-url-without-https>
        headers:
          Authorization: Bearer <token>

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging, otlp/elastic]
        traces:
          processors: [memory_limiter, resource, batch]
          exporters: [otlp, logging, otlp/elastic]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, filter/ottl, transform, resource, batch]
          exporters: [prometheus, logging, otlp/elastic]

jaeger:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false
