components:
  loadgenerator:
    enabled: false
  frontend:
    resources:
      limits:
        memory: 500Mi

opentelemetry-collector:
  config:
    exporters:
      ## Create an exporter to Tempo using the standard `otlp` export format
      otlp:
        endpoint: 'grafana-k8s-monitoring-grafana-agent.default.svc.cluster.local:4317'
        tls:
          insecure: true

prometheus:
  enabled: false

jaeger:
  enabled: false

grafana:
  enabled: false
