components:
  frontend:
    resources:
      limits:
        memory: 500Mi

opentelemetry-collector:
  config:
    exporters:
      otlp:
        endpoint: 'grafana-k8s-monitoring-grafana-agent.default.svc.cluster.local:4317'
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, spanmetrics]
        metrics:
          receivers: [otlp, spanmetrics]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]

prometheus:
  enabled: false

jaeger:
  enabled: false

grafana:
  enabled: false
