apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-corrupt-example
  namespace: chaos-testing
spec:
  action: corrupt
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app.kubernetes.io/instance: my-otel-demo
  corrupt:
    corrupt: "40"
    correlation: "25"
  duration: "10s"
