apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  namespace: default
  name: pod-failure-example
spec:
  selector:
    namespaces:
      - default # the namespace of the system under test (SUT) you've deployed
    labelSelectors:
      app.kubernetes.io/instance: my-otel-demo # the label of the pod for chaos injection
  mode: all # the mode to run chaos action; supported modes are one/all/fixed/fixed-percent/random-max-percent
  action: pod-failure # the specific chaos action to inject; supported actions: pod-kill/pod-failure/container-kill
  duration: 60s # duration for the injected chaos experiment
